# fly.toml file generated for lively-shadow-9874 on 2023-02-25T01:02:53+03:00

app = "lively-shadow-9874"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "arigatory/restore:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  StripeSettings__PublishableKey="pk_test_51MTVr6BrFzsPxqJgGHuMvcbEa4FriwUdvfErMVlwa5kbY66p44QaZ1apK3itJpQEIIphuyIDplLc4eZBxE0SdOfV00ujo2Fuar"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
